backend:
  name: gitlab
  # repo: owner-name/repo-name # Path to your GitLab repository
  # auth_type: implicit # Required for implicit grant
  # app_id: your-app-id # Application ID from your GitLab settings

# display_url: https://app.tenant.com
media_folder: "solution/admin/media"

collections:
  - name: "tenant_suites"
    label: "Suites"
    label_singular: "Suite"
    delete: false
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - name: "suites"
        label: "Suites"
        file:  "solution/data/tenants/suites.json"
        description: "VuePoint.js Tenant Suites"
        fields:
          - name: "suites"
            label: "Suites"
            label_singular: "Suite"
            widget: "list"
            fields:
              - {name: "key", label: "Suite Key", widget: "string", pattern:["^[A-Z]{1}([0-9]|[A-Z]){3}$", "1 letter followed by 3 letters or numbers, all uppercase"]}
              - {name: "name", label: "Suite Name", widget: "string", pattern:[".{2,30}", "Min 2, Max 30 characters"]}
              - {name: "shortName", label: "Suite Short Name", widget: "string", pattern:[".{2,12}", "Min 2, Max 12 characters"]}
              - {name: "tenantKey", label: "Tenant Key", widget: "string", pattern:[".{2,4}", "Min 2, Max 4 characters"]}
              - {name: "tenantName", label: "Tenant Name", widget: "string", pattern:[".{2,30}", "Min 2, Max 30 characters"]}
              - name: "apps"
                label: "Apps"
                label_singular: "App"
                widget: "list"
                fields:
                  - {name: "key", label: "App Key", widget: "string", pattern:["^[A-Z]{1}([0-9]|[A-Z]){1}$", "1 letter followed by 1 letter or number, all uppercase"]}
                  - {name: "name", label: "App Short Name", widget: "string", pattern:[".{2,16}", "Min 2, Max 16 characters"]}
                  - {name: "longName", label: "App Name", widget: "string", pattern:[".{2,30}", "Min 2, Max 30 characters"]}
                  - name: "applets"
                    label: "Applets"
                    label_singular: "Applet"
                    widget: "list"
                    fields:
                      - {name: "key", label: "Applet Key", widget: "string", pattern:["^[A-Z]{1}([0-9]|[A-Z]){1}$", "1 letter followed by 1 letter or number, all uppercase"]}
                      - {name: "title", label: "Applet Key", widget: "string", pattern:["^[A-Z]{1}([0-9]|[a-zA-Z]){1}$", "1 uppercase letter followed by 1 letter or number"]}
                      - {name: "ord", label: "Display Order", widget: "number", valueType: "int", min: 1, max: 2000000}
                      - {name: "name", label: "App Short Name", widget: "string", pattern:[".{2,16}", "Min 2, Max 16 characters"]}
                      - {name: "longName", label: "App Name", widget: "string", pattern:[".{2,30}", "Min 2, Max 30 characters"]}
                      - name: "views"
                        label: "Views"
                        label_singular: "View"
                        widget: "list"
                        fields:
                          - {name: "title", label: "Title", widget: "string", pattern:[".{2,30}", "Min 2, Max 30 characters"]}
                          - {name: "default", label: "Applet Home Page?", widget: "boolean", default: false, required: true}
                          - name: "type"
                            label: "Type"
                            widget: "select"
                            options:
                              - { label: "Custom Content Page", value: "page" }
                              - { label: "List", value: "list" }
                              - { label: "Add", value: "add" }
                              - { label: "Edit", value: "edit" }
                              - { label: "Delete", value: "delete" }
                              - { label: "Merge", value: "merge" }
                          - name: "subType"
                            label: "Sub Type"
                            widget: "select"
                            options:
                              - { label: "Body as Markdown", value: "body-as-markdown" } # valid for type: page
                              - { label: "Items as Cards/Tiles", value: "items-as-cards" } # valid for type: list
                              - { label: "Items as Grid", value: "items-as-grid" } # valid for type: list
                              - { label: "Add", value: "add" }
                              - { label: "Edit", value: "edit" }
                              - { label: "Delete", value: "delete" }
                              - { label: "Merge", value: "merge" }
  