backend:
  name: gitlab
  # repo: owner-name/repo-name # Path to your GitLab repository
  # auth_type: implicit # Required for implicit grant
  # app_id: your-app-id # Application ID from your GitLab settings

# display_url: https://app.tenant.com
media_folder: "solution/admin/media"

collections:
  - name: "tenant_suites"
    label: "Configuration"
    label_singular: "Suite"
    delete: false
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - name: "suites"
        label: "> Administer Suites, Apps, Applets, and Views"
        file:  "solution/data/tenants/suites.json"
        description: "VuePoint.js Tenant Suites"
        fields:
          - name: "suites"
            label: "Configurations"
            label_singular: "Configuration"
            widget: "list"
            fields: # NOTE: Known flaw in Netlify CMS prevents validation of nested fields for now... https://github.com/netlify/netlify-cms/issues/467
              - {name: "name", label: "Suite Short Name", widget: "string", pattern: [".{2,12}", "Min 2, Max 12 characters"]}
              - {name: "key", label: "Suite Key", widget: "string", pattern: ["^[A-Z]{1}([0-9]|[A-Z]){1,3}$", "1 letter followed by 1 to 3 letters or numbers, all uppercase"]}
              - {name: "longName", label: "Suite Long Name", widget: "string", pattern: [".{2,30}", "Min 2, Max 30 characters"]}
              - {name: "tenantKey", label: "Tenant Key", widget: "string", pattern: [".{2,4}", "Min 2, Max 4 characters"]}
              - {name: "tenantName", label: "Tenant Name", widget: "string", pattern: [".{2,30}", "Min 2, Max 30 characters"]}
              - name: "azureConfigurations"
                label: "Azure Configurations"
                label_singular: "Azure Configuration"
                widget: "list"
                fields:
                  - {name: "key", label: "Configuration Key", widget: "string", pattern: ["^[A-Z]{2,4}$", "2 to 4 letters, all uppercase. For example: DEV, PROD, etc."]}
                  - {name: "tenantHostName", label: "O365 Tenant Host Name", widget: "string", required: false, pattern: ["^[a-fA-F]{1}[0-9a-fA-F]{2,31}.onmicrosoft.com$", "<tenant-name>.onmicrosoft.com"]}
                  - {name: "clientId", label: "Azure-registered Client ID", widget: "string", required: false, pattern: ["^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", "32 hexadecimal digits, hyphenated, no curly braces"]}
                  - {name: "apiId", label: "Azure-registered API ID", widget: "string", required: false, pattern: ["^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", "32 hexadecimal digits, hyphenated, no curly braces"]}
                  - {name: "redirectUri", label: "Azure-registered Client Redirect Uri", widget: "string", required: false, pattern: ['(http[s]?:\/\/)?[^\s(["<,>]*\.[^\s[",><]*', "A valid URI starting with http or https"]}
              - name: "apps"
                label: "Apps"
                label_singular: "App"
                widget: "list"
                fields:
                  - {name: "name", label: "App Short Name", widget: "string", pattern: [".{2,16}", "Min 2, Max 16 characters"]}
                  - {name: "key", label: "App Key", widget: "string", pattern: ["^[A-Z]{1}([0-9]|[A-Z]){1}$", "1 letter followed by 1 letter or number, all uppercase"]}
                  - {name: "longName", label: "App Long Name", widget: "string", pattern: [".{2,30}", "Min 2, Max 30 characters"]}
                  - name: "applets"
                    label: "Applets"
                    label_singular: "Applet"
                    widget: "list"
                    fields:
                      - {name: "name", label: "Applet Short Name", widget: "string", pattern: [".{2,12}", "Min 2, Max 12 characters"]}
                      - {name: "key", label: "Applet Key", widget: "string", pattern: ["^[A-Z]{1}([0-9]|[A-Z]){1}$", "1 letter followed by 1 letter or number, all uppercase"]}
                      - {name: "iconLabel", label: "Applet Icon Label", widget: "string", pattern: ["^[A-Z]{1}([0-9]|[a-zA-Z]){1}$", "1 uppercase letter followed by 1 letter or number"]}
                      - {name: "ord", label: "Applet Display Order", widget: "number", valueType: "int", min: 1, max: 2000000}
                      - {name: "longName", label: "Applet Long Name", widget: "string", pattern: [".{2,30}", "Min 2, Max 30 characters"]}
                      - name: "views"
                        label: "Views"
                        label_singular: "View"
                        widget: "list"
                        fields:
                          - {name: "name", label: "View Name", widget: "string", pattern: [".{2,30}", "Min 2, Max 30 characters"]}
                          - {name: "default", label: "View is Applet Home Page?", widget: "boolean", default: false, required: true}
                          - name: "type"
                            label: "View Type"
                            widget: "select"
                            options:
                              - { label: "Custom Content Page", value: "page" }
                              - { label: "List", value: "list" }
                              - { label: "Add", value: "add" }
                              - { label: "Edit", value: "edit" }
                              - { label: "Delete", value: "delete" }
                              - { label: "Merge", value: "merge" }
                          - name: "subType"
                            label: "View Sub Type"
                            widget: "select"
                            options:
                              - { label: "Body as Markdown", value: "body-as-markdown" } # valid for type: page
                              - { label: "Items as Cards/Tiles", value: "items-as-cards" } # valid for type: list
                              - { label: "Items as Grid", value: "items-as-grid" } # valid for type: list
                              - { label: "Add", value: "add" }
                              - { label: "Edit", value: "edit" }
                              - { label: "Delete", value: "delete" }
                              - { label: "Merge", value: "merge" }
