apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zz-demo-deployment
  labels:
    app: zz-demo
spec:
  replicas: 1
  template:
    metadata:
      name: zz-demo
      labels:
        app: zz-demo
    spec:
      containers:
        - name: zz-demo
          image: vpdemocontainers.azurecr.io/zz-demo:1.0.0-alpha.1
          imagePullPolicy: IfNotPresent
          # tty: true
          # command: ["maybe?"]
          ports:
            - containerPort: 443
      restartPolicy: Always
  selector:
    matchLabels:
      app: zz-demo

---
apiVersion: v1
kind: Service
metadata:
  name: zz-demo-service
spec:
  selector:
    app: zz-demo
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zz-demo-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: zz-demo-ingress.eeeeeeeeeedddddddddd.eastus.aksapp.io
      http:
        paths:
          - backend:
              serviceName: zz-demo-service
              servicePort: 443
            path: /
